const assert=require('node:assert/strict');
const ts=require('typescript');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {createRequire}=require('node:module');
const source=path.resolve('lib/model.ts');
const code=ts.transpileModule(fs.readFileSync(source,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
const moduleResult={exports:{}};vm.runInNewContext(code,{exports:moduleResult.exports,require:createRequire(source)});
const {summary,validField}=moduleResult.exports;
assert.equal(summary(()=>null,'de').grade,null);
assert.equal(summary(k=>k.includes('.score.')?0:null,'de').grade,1);
assert.equal(summary(k=>k.includes('.score.')?4:null,'de').total,32);
assert.equal(summary(k=>k.includes('.score.')?4:null,'de').grade,6);
assert.equal(summary(k=>k==='storyboard'?'missing':k.includes('.score.')?4:null,'de').total,28);
assert.equal(summary(k=>k==='storyboard'?'missing':null,'ko').count,1);
assert.equal(summary(k=>k==='de.score.0'?4:null,'de').total,8);
assert.equal(summary(k=>k.includes('.score.')?3:null,'ko','0.5').grade,5);
assert.equal(summary(k=>k.includes('.score.')?3:null,'ko','0').grade,4.75);
assert.equal(validField('room','rounding','0.2'),false);
assert.equal(validField('film','de.score.0',NaN),false);
console.log('PASS: weighted scoring, 0 versus unassessed, missing storyboard, two rounding modes, validation.');
